import type { Film } from "../interfaces/Pelicula.ts";

const peliculas: Array<Film> = [
  {
    id: 1,
    titulo: "The Shawshank Redemption",
    generos: "Drama",
    anio: 1994,
    director: "Frank Darabont",
    likes: 1850,
    portada: "https://m.media-amazon.com/images/I/51NiGlapXlL._AC_.jpg",
    duracion: 142,
  },
  {
    id: 2,
    titulo: "The Godfather",
    generos: "Crime ,Drama",
    anio: 1972,
    director: "Francis Ford Coppola",
    likes: 2100,
    portada: "https://m.media-amazon.com/images/I/41+eK8zBwQL._AC_.jpg",
    duracion: 175,
  },
  {
    id: 3,
    titulo: "The Dark Knight",
    generos: "Action ,Crime, Drama",
    anio: 2008,
    director: "Christopher Nolan",
    likes: 2800,
    portada: "https://m.media-amazon.com/images/I/51k0qa6zY-L._AC_.jpg",
    duracion: 152,
  },
  {
    id: 4,
    titulo: "Pulp Fiction",
    generos: "Crime, Drama",
    anio: 1994,
    director: "Quentin Tarantino",
    likes: 1700,
    portada: "https://m.media-amazon.com/images/I/51V5ZpFyaFL._AC_.jpg",
    duracion: 154,
  },
  {
    id: 5,
    titulo: "Inception",
    generos: "Action , Adventure, Sci-Fi",
    anio: 2010,
    director: "Christopher Nolan",
    likes: 2600,
    portada: "https://m.media-amazon.com/images/I/5101fG3r+SL._AC_.jpg",
    duracion: 148,
  },
  {
    id: 6,
    titulo: "Fight Club",
    generos: "Drama",
    anio: 1999,
    director: "David Fincher",
    likes: 1900,
    portada: "https://m.media-amazon.com/images/I/5190M4JGkRL._AC_.jpg",
    duracion: 139,
  },
  {
    id: 7,
    titulo: "Forrest Gump",
    generos: "Drama, Romance",
    anio: 1994,
    director: "Robert Zemeckis",
    likes: 2400,
    portada: "https://m.media-amazon.com/images/I/41cMxNsyfqL._AC_.jpg",
    duracion: 142,
  },
  {
    id: 8,
    titulo: "The Matrix",
    generos: "Action, Sci-Fi",
    anio: 1999,
    director: "Lana Wachowski, Lilly Wachowski",
    likes: 2200,
    portada: "https://m.media-amazon.com/images/I/51vpnbwFHrL._AC_.jpg",
    duracion: 136,
  },
  {
    id: 9,
    titulo: "Interstellar",
    generos: "Adventure, Drama, Sci-Fi",
    anio: 2014,
    director: "Christopher Nolan",
    likes: 2500,
    portada: "https://m.media-amazon.com/images/I/81kEwrIXsfL._AC_SL1500_.jpg",
    duracion: 169,
  },
  {
    id: 10,
    titulo: "Gladiator",
    generos: "Action, Adventure, Drama",
    anio: 2000,
    director: "Ridley Scott",
    likes: 1800,
    portada: "https://m.media-amazon.com/images/I/51A9FjO5hFL._AC_.jpg",
    duracion: 155,
  },
  {
    id: 11,
    titulo: "Titanic",
    generos: "Drama ,Romance",
    anio: 1997,
    director: "James Cameron",
    likes: 2300,
    portada:
      "https://www.originalfilmart.com/cdn/shop/products/titanic_1997_original_film_art_713cc08c-5fe2-49d1-bd32-51a1d5890d43_5000x.jpg?v=1675533926",
    duracion: 195,
  },
  {
    id: 12,
    titulo: "The Lord of the Rings: The Fellowship of the Ring",
    generos: "Adventure ,Drama, Fantasy",
    anio: 2001,
    director: "Peter Jackson",
    likes: 2600,
    portada: "https://m.media-amazon.com/images/I/51Qvs9i5a%2BL._AC_.jpg",
    duracion: 178,
  },
  {
    id: 13,
    titulo: "The Silence of the Lambs",
    generos: "Crime, Drama ,Thriller",
    anio: 1991,
    director: "Jonathan Demme",
    likes: 1700,
    portada: "https://m.media-amazon.com/images/I/41n4xXat93L._AC_.jpg",
    duracion: 118,
  },
  {
    id: 14,
    titulo: "Saving Private Ryan",
    generos: "Drama, War",
    anio: 1998,
    director: "Steven Spielberg",
    likes: 2100,
    portada: "https://m.media-amazon.com/images/I/51k0qa6zY-L._AC_.jpg",
    duracion: 169,
  },
  {
    id: 15,
    titulo: "The Green Mile",
    generos: "Crime, Drama, Fantasy",
    anio: 1999,
    director: "Frank Darabont",
    likes: 1800,
    portada: "https://m.media-amazon.com/images/I/51zUbui+gbL._AC_.jpg",
    duracion: 189,
  },
  {
    id: 16,
    titulo: "Whiplash",
    generos: "Drama ,Music",
    anio: 2014,
    director: "Damien Chazelle",
    likes: 1700,
    portada: "https://m.media-amazon.com/images/I/71t6l4UttwL._AC_SY679_.jpg",
    duracion: 106,
  },
  {
    id: 17,
    titulo: "The Departed",
    generos: "Crime, Drama, Thriller",
    anio: 2006,
    director: "Martin Scorsese",
    likes: 1600,
    portada: "https://m.media-amazon.com/images/I/51L8fLqDFTL._AC_.jpg",
    duracion: 151,
  },
  {
    id: 18,
    titulo: "Joker",
    generos: "Crime, Drama, Thriller",
    anio: 2019,
    director: "Todd Phillips",
    likes: 2300,
    portada: "https://m.media-amazon.com/images/I/71hZEGH8TPL._AC_SL1111_.jpg",
    duracion: 122,
  },
  {
    id: 19,
    titulo: "Parasite",
    generos: "Comedy, Drama, Thriller",
    anio: 2019,
    director: "Bong Joon-ho",
    likes: 2100,
    portada: "https://m.media-amazon.com/images/I/91nPthc8LfL._AC_SL1500_.jpg",
    duracion: 132,
  },
  {
    id: 20,
    titulo: "The Prestige",
    generos: "Drama, Mystery, Sci-Fi",
    anio: 2006,
    director: "Christopher Nolan",
    likes: 1900,
    portada: "https://m.media-amazon.com/images/I/51hQ9xuz5tL._AC_.jpg",
    duracion: 130,
  },
];

export default peliculas;
